<?php if ($this->pageCount > 1): ?>
    <div class="pagination">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('action' => $action, 'page' => $this->previous, 'order_by' => $order_by, 'order' => $order,)); ?>">
                        前へ
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, array('action' => $action, 'page' => $page, 'order_by' => $order_by, 'order' => $order,)); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('action' => $action, 'page' => $this->next, 'order_by' => $order_by, 'order' => $order,)); ?>">
                       次へ
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>